name: medlens-graphrag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi
      - uvicorn
      - python-dotenv
      - python-multipart
      - requests
      - pydantic
      - pandas
      - pyarrow
      - networkx
      - numpy
      - scikit-learn
      - lancedb
      - sentence-transformers
      - aiofiles
      - tqdm
